Repository windup/windup, pull requests merged in 2023-03, with the labels that each got.

#1518 Windup 3370 export summary file
  exec/api/src/main/java/org/jboss/windup/exec/configuration/WindupConfiguration.java
  exec/api/src/main/java/org/jboss/windup/exec/configuration/options/ExportSummaryOption.java
  exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
  graph/api/src/main/java/org/jboss/windup/graph/model/WindupConfigurationModel.java
  reporting/impl/pom.xml
  rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProvider.java
  rules-java/tests/src/test/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProviderTest.java
  rules-java/tests/src/test/resources/issueSummary/app1/HelloWorld.java
  rules-java/tests/src/test/resources/issueSummary/app2/HelloWorld.java
Labels: Ready to Review

#1604 WINDUP-3715 Enabled multiple transformations for a single source/target input value
  config-xml/addon/src/main/java/org/jboss/windup/config/parser/XMLTechnologyReferenceAliasTranslatorLoader.java
  exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
  exec/tests/pom.xml
  exec/tests/src/test/java/org/jboss/windup/exec/test/TechnologyReferenceTransformersTest.java
  exec/tests/src/test/resources/sample.windup.technologytransformer.xml
Labels: Ready to Review

#1606 WINDUP-3720 Decoupled JSON extract generation from reports rendering
  rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProvider.java
  rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateJsonSummaryRuleProvider.java
  rules-java/tests/src/test/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProviderTest.java
Labels: Ready to Review

#1611 WINDUP-3722 Added param to use 'search.maven.org' website
  rules-java/api/src/main/resources/reports/templates/dependency_report.ftl
  rules-java/api/src/main/resources/reports/templates/java_application.ftl
Labels: Ready to Review

#1612 [WINDUP-3725] Fix annotated-type condition on javaclass other than location=ANNOTATION
  rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/AnalyzeJavaFilesRuleProvider.java
Labels: Ready to Review

#1613 WINDUP-3748 Refactored 'deleteGraphDataUnlessInhibited' method
  bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
  exec/api/src/main/java/org/jboss/windup/exec/Util.java
Labels: Ready to Review

#1619 Bump Nexus index 23.03.23.Final
  bom/pom.xml
Labels: auto-backport, auto-backport-to-releases/6.1.z

#1623 WINDUP-3612 non-zero RC when failing an analysis
  bootstrap/src/main/java/org/jboss/windup/bootstrap/Bootstrap.java
  bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/DisplayHelpCommand.java
  bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.1.z

#1624 [WINDUP-3726] Fix tech intersection
  reporting/api/src/main/java/org/jboss/windup/reporting/config/TechnologiesIntersector.java
  reporting/tests/src/test/java/org/jboss/windup/reporting/config/TechnologiesIntersectorTest.java
Labels: Ready to Review
