Repository windup/windup, pull requests merged in 2023-04, with the labels that each got.

#1628 [WINDUP-3767] Check for user rule files leaking as input
  reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
Labels: Ready to Review

#1630 Added 'legacyReports' option management
  bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ToolingModeCommand.java
  tooling/api/src/main/java/org/jboss/windup/tooling/IOptionKeys.java
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#1633 Bump Node v16.20.0 - NPM 8.19.4
  pf-ui/pom.xml
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#1637 WINDUP-3793 ZIP creation: add 'logs' folder to excluded prefixes list
  exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
  reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportZipReportRuleProvider.java
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#1640 WINDUP-3805 'Collapse all' typo
  pf-ui/src/main/webapp/src/pages/application-edit/pages/details/components/application-files-table.tsx
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#1645 WINDUP-3812 Bump maven-artifact 3.9.1
  rules-java/api/pom.xml
  rules-java/tests/src/test/java/org/jboss/windup/rules/java/VersionTest.java
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#1643 MTA-458 Enhanced the input values management
  bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
Labels: Ready to Review

#1642 [WINDUP-3809] - Improper alignment in case of file without references to source code.
  pf-ui/src/main/webapp/src/shared/components/issues-table/components/issue-overview.tsx
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#1646 [WINDUP-3813] - "View rule" with Java rule has broken syntax highlighting
  pf-ui/src/main/webapp/src/shared/components/rule-editor/rule-editor.tsx
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#1653 [WINDUP-3839] - New reports: issues reported twice in "Details" file
  pf-ui/src/main/webapp/src/pages/application-edit/pages/details/components/application-files-children-table.tsx
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#1654 [WINDUP-3840] - New reports: Rules report is missing the ruleset ID
  pf-ui/src/main/webapp/src/api/rule.ts
  pf-ui/src/main/webapp/src/pages/rules-list/rules-list.tsx
  pf-ui/src/main/webapp/src/queries/mocks/rules.mock.ts
  reporting-data/addon/src/main/java/org/jboss/windup/reporting/data/dto/RuleDto.java
  reporting-data/addon/src/main/java/org/jboss/windup/reporting/data/rules/RulesRuleProvider.java
Labels: auto-backport, auto-backport-to-releases/6.2.z

#1651 WINDUP-3843 Fix source filter for issues table component
  pf-ui/src/main/webapp/src/shared/components/issues-table/issues-table.tsx
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z

#1652 [WINDUP-3842] - Source code window not in sync with the Issues reported
  pf-ui/src/main/webapp/src/shared/components/issues-table/components/issue-overview.tsx
  pf-ui/src/main/webapp/src/shared/components/issues-table/issues-table.tsx
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.2.z
