Repository windup/windup, pull requests merged in 2024-01, with the labels that each got.

#1714 [WINDUP-4117] - Upgrade follow-redirect
  pf-ui/src/main/webapp/package-lock.json
  pf-ui/src/main/webapp/package.json
Labels: Ready to Review, auto-backport-to-releases/6.3.z

#1715 [WINDUP-3958] - Upgrade tough-cookie
  pf-ui/src/main/webapp/package-lock.json
  pf-ui/src/main/webapp/package.json
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.3.z

#1716 [WINDUP-3963] - Upgrade semver
  pf-ui/src/main/webapp/package-lock.json
  pf-ui/src/main/webapp/package.json
Labels: Ready to Review, auto-backport, auto-backport-to-releases/6.3.z

#1720 WINDUP-4028 upgrade ivy version
  graph/api/pom.xml
Labels: auto-backport, auto-backport-to-releases/6.3.z
